spring:
  profiles: dev

server:
  port: 80

telegrambot:
  userName:
  botToken:
  botPath: "/jobby"
  webHookPath:

---
spring:
  profiles: prod

server:
  port: ${PORT:8080}

telegrambot:
  userName: ${BOT_USERNAME}
  botToken: ${BOT_TOKEN}
  botPath: "/jobby"
  webHookPath: ${BOT_WEBHOOK}
