spring:
  datasource:
    generate-unique-name: false
    name: jobbyDB
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false

telegrambot:
  botUsername: ${BOT_USERNAME:}
  botToken: ${BOT_TOKEN:}
  botPath: "/jobby"
  webHookPath: ${BOT_WEBHOOK:}

searchPeriod:
  minute: 30

---
spring:
  config:
    activate:
      on-profile:
        - prod

  datasource:
    generate-unique-name: false
    name: jobbyDB
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:8080}

telegrambot:
  botUsername: ${BOT_USERNAME}
  botToken: ${BOT_TOKEN}
  botPath: "/jobby"
  webHookPath: ${BOT_WEBHOOK}

searchPeriod:
  minute: 30