spring:
  config:
    activate:
      on-profile:
        - dev

  datasource:
    generate-unique-name: false
    name: jobbyDB
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true

telegrambot:
  botUsername:
  botToken:
  botPath: "/jobby"
  webHookPath:

searchPeriod:
  minute: 30

---
spring:
  config:
    activate:
      on-profile:
        - prod

server:
  port: ${PORT:8080}

telegrambot:
  botUsername: ${BOT_USERNAME}
  botToken: ${BOT_TOKEN}
  botPath: "/jobby"
  webHookPath: ${BOT_WEBHOOK}
